### ISSUE TITLE
✍️ Contribution period: <Akriti Dhurandher> 

### ISSUE THREAD

**Issue by akriti-dhurandher** [ersilia-os/ersilia#1030]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Install Docker if needed, and test another model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [x] Select a model from the list suggested in GitBook
- [x] Download and serve the model via the Ersilia Model Hub to ensure it works
- [x] Open a repository on your GitHub user with all the necessary files
- [x] Select and clean a dataset of 1000 molecules (example notebook 1)
- [x] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [ ] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by akriti-dhurandher** [comment]
Hello, I am Akriti and as elated I was to make it through the initial applications in Outreachy, I was amazed to have found Ersilia as well. I have had experience with machine learning and some deep learning where I worked with CNNs and images and I worked towards sustainable agriculture since then I have viewed AI/ML as the biggest tool for sustainable development and research. 
I familiarized with Ersilia within the first day because my core morals inclined so much with it's vision. I have found the tech stack for this project astounding and it will be my first project involving docker and an open source project, thus this project has not only pushed me to work towards my interests but also to learn new skills that will prove invaluable. Since I am an AI/ML enthusiast Ersilia has provided me a whole new domain to experiment my skills and grab on to new ones through this project. 
If I proceed to be candid, the society I come from the practicality of your dreams become a measure of their fulfilment but I want to break out of it and with Ersilia I believe I can work towards my aim of research and development using AI/ML that too towards a novel cause of finding drugs for disease which are often neglected. I aim to be a  vehemently devoted contributor and learner towards this project with Ersilia in the coming weeks.

**Comment by akriti-dhurandher** [comment]
Anecdote on my learnings post **WEEK 1** Tasks,

- I learned the use of Docker
- Familiarized myself with uses of ML in Chemistry and Drug discovery
- Finalized the Model **eos30gr** work with
- Also considering model **eos6oli** as an alternative 

### **WEEK 2** 
**Task 1**

- Using the Model usage page set up and run the Model on the **1000 molecule ** dataset made available in the data channel in slack
- The model **eos30gr** is a classification model that works on hERG Blockade
-Forked a repository from model validation template
-Provided a .ipynb file with detailed visualizations on the outputs

**Task 2**
To start


Repository link

https://github.com/akriti-dhurandher/model-validation-example

**Comment by akriti-dhurandher** [comment]
Hello @DhanshreeA could you review my tasks until now and let me know if I'm proceeding correctly?

**Comment by akriti-dhurandher** [comment]
Hello @DhanshreeA I was proceeding with week 2 task 2 and 3 , can you please let me know the review of task 1

**Comment by akriti-dhurandher** [comment]
I started the 2nd task and obtained results working on the author/publications model using their used dataset.
https://jcheminf.biomedcentral.com/articles/10.1186/s13321-021-00541-z
https://github.com/Abdulk084/CardioTox

**Comment by akriti-dhurandher** [comment]
![Screenshot 2024-03-21 205636](https://github.com/ersilia-os/ersilia/assets/120331680/a3a8d423-7fc8-4de6-9343-e6fbfedd8f37)

- Run the model on the dataset of the author, used their test dataset for Task 2: Reproducibility
- Compared the results obtained by author , to results I obtained via running the model

**Comment by akriti-dhurandher** [comment]
Hello @GemmaTuron and @DhanshreeA , I have completed all my tasks of week 2 and am awaiting your feedback to either update or proceed further with week 3 tasks

**Comment by DhanshreeA** [comment]
> Hello @DhanshreeA could you review my tasks until now and let me know if I'm proceeding correctly?

Hi @akriti-dhurandher good work so far with T1

**Comment by DhanshreeA** [comment]
@akriti-dhurandher I am unsure if you are working with model eos30gr or eos2ta5? You have referenced the paper and implementation for eos2ta5, but you mention working with eos30gr. Could you confirm which one you chose?

**Comment by akriti-dhurandher** [comment]
Hi @DhanshreeA , thank you for pointing to my mistake , I actually was unable to locate the model and asked a peer for help and they sent me this link , I too was confused a bit but thought of them as same , Right now I stand overwhelmed could you guide me on what to do next

**Comment by DhanshreeA** [comment]
Since you have the dataset for model eos2ta5, why don't you re run the code for T1 and T2 using the model eos2ta5, instead of eos30gr? I can review again on Monday and provide some final feedback.

**Comment by akriti-dhurandher** [comment]
Hey, @DhanshreeA thanks , and I was just proceeding with the same , as all this work from past 2 weeks has made it easier understanding all the similar models and concepts , When I explored the model eos2ta5, I could very well understand what was happening and I am positive with this shift now, I am moving ahead with redoing all the tasks with eos2ta5 this time , hope I do even better this time also faster!

**Comment by akriti-dhurandher** [comment]
Hello @DhanshreeA , I have updated my repo with results for model eos2ta5 and I am proceeding for task 3, meanwhile I await your reviews and suggestions.
Due to some complications with settings of my local machine I had to push the whole of my jupyter notebook as the tasks , but I have kept the format strictly same as those provided in the sample repo 
Here's the link to my updated work

- https://github.com/akriti-dhurandher/model-validation-example
- Please find my work under the files:
- week2_task1 
- week2_task2

**Comment by GemmaTuron** [comment]
Hi @akriti-dhurandher 
Please now that the changes are pushed, please work on cleaning the repository as it is a bit difficult to follow.
I suggest also making some changes on the graphs, instead of pie charts it would be good to see a scatter plot in the reproducibility task showing the real model vs ersilia implementation results

Once this is done, explain it here with your conclusions and move onto preparing your final application

**Comment by akriti-dhurandher** [comment]
Hi, @GemmaTuron , surely I will make the suggested changes make a elaborate and clear explanation here.
Thank you

**Comment by akriti-dhurandher** [comment]
Adhering to my latest feedback from @GemmaTuron , here is the detailed explanation of my work on T2

1. Run the authors model using WSL, as guided in he repository : https://github.com/Abdulk084/CardioTox
2. Obtained the results, below is a snapshot depicting the same

![image](https://github.com/ersilia-os/ersilia/assets/120331680/c1452ba7-1295-4f4d-ab14-4f88a3992eb3)

3. Now taking the test set from the authors model and putting them in use for the Ersilia model **eos2ta5** using test set-I 
4. Obtained the results as snapshot below shows
![image](https://github.com/ersilia-os/ersilia/assets/120331680/0c4d61a3-e5d2-4b27-b8c3-4dbbcd826dee)

5. These results were extracted in.csv format and same was done with test set-II
![image](https://github.com/ersilia-os/ersilia/assets/120331680/b65cc78a-0588-4ec7-92d6-9489992ef6da)

6. From reference table :https://jcheminf.biomedcentral.com/articles/10.1186/s13321-021-00541-z/tables/4
    and the reproduced results when I ran the authors model gave same results, which I have tabulated 
    below for review:
![image](https://github.com/ersilia-os/ersilia/assets/120331680/749bf69d-ac97-4134-af8a-54578d1cebe8)

 Thus the model was reproducible 

7. Further I have updated my repo :
    as suggest in my last feedback from @GemmaTuron , I have run the Ersilia model for both the available test data sets and plotted scatter plots for some inferences

8. Lastly as I was to clean my repository, I have done so by well organizing all the input/output csv's into the data folder and my tasks could be found in the notebook folder named 
-Week2_task1
-Week2_task2
9. Now I ma proceeding with drafting  my final application

@GemmaTuron and @DhanshreeA  I hope to get one final feedback on my work in my repo while I prepare my final application , Thank you.
