### ISSUE TITLE
[🐅 Epic]: Splunk Integration into Ersilia

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1090]
### Summary
Ersilia is host to a number of models that only keeps growing. With the advancements in Generative AI in drug discovery, we are now incorporating compute intensive models into the model hub. Ersilia's primary stakeholders are scientists and researchers working with limited resources and therefore it is imperative that we collect performance metrics related to a model's run after it is incorporated in Ersilia. This work has multiple aspects:

- the actual collection of a model run metrics
- persisting these metrics in a remote collection
- visualization of these metrics in a dashboard (powered by Splunk Enterprise) 
- monitoring and visualizing these metrics at scale per model (this will be enabled in conjunction through the work done by GDI at https://github.com/ersilia-os/model-inference-pipeline)

We want to test and integrate the `ersilia run --track` flag more closely within our workflows and use of the Splunk powered Ersilia Model TA dashboard as a way to closely monitor models within the Ersilia Model Hub. 

### Objective(s)

The project is divided into code refactoring tasks and then various phases of Splunk integration, and finally tasks related to making the dashboard accessible over the web. These tasks can be executed independent of each other unless specified otherwise.

**Prerequisites**

- [x] Test the track flag locally to see if it produces the desired results on your machine

**Code Refactoring**:
- [x] Remove Pandas as a dependency by using the natively in built csv module instead (#928 and #1054)
- [x] Resolve duplication between `RunLogger` in `ersilia/core/session.py` and `RunTracker` in `ersilia/core/tracking.py`. For example, both RunTracker and RunLogger subsample result output when the output dimensions are too many to reduce storage overhead, and to not clutter the monitoring dashboard. https://github.com/ersilia-os/ersilia/pull/1132
- [x] Remove multiple, redundant, tracking flags and and keep a single boolean flag with a default False value such that by default we do not track runs for now. https://github.com/ersilia-os/ersilia/pull/1160
- [x] Rework code calculating memory usage - output and Docker container https://github.com/ersilia-os/ersilia/issues/1162
- [x] Bug: The tracking flag does not currently work when a CSV file is not specified for storing the model predictions. https://github.com/ersilia-os/ersilia/issues/1164

**Phased Integration**:
- [ ] Phase 0.1: Integrate tracking command within Ersilia model test pipeline prior to refactoring and benchmark this (#925)
- [ ] Phase 0.2: Stress testing a model and computing performance and resource usage with different input scenarios and systems
- [ ] Phase 1: Write an action to update model metadata with [system requirements](https://github.com/ersilia-os/ersilia/issues/782) for CPU and RAM currently (future to include GPU), plus updating this in Airtable
- [ ] Phase 2: Combine track command with GDI Pipeline
- [ ] Phase 3: Make use of track command within user requested model runs within the [ersilia-self-service](https://github.com/ersilia-os/ersilia-self-service) repository. 

Notes: 

- Code Refactoring task 1 should be done on a separate branch as opposed to master to verify that we still get the same results from both the original implementation and the refactored code. 
- Each of the tasks will be handled in a separate PR wherever applicable.
- The track command produces outputs in a folder called ersilia-runs within the EOS directory in a user's HOME folder. When the user has access to write credentials for Ersilia's S3 buckets, these run data should be populated there.

**Splunk Usability and Dashboard**: 

- [x] Verify model tracking results being uploaded to S3. Related issue: #1220 
- [x] Verify that the Ersilia Model TA app is successfully consuming from the S3 bucket from the previous point.
- [x] Verify and potentially extend or rewrite the Ersilia Model TA app.
- [ ] Expose Ersilia Model TA dashboard behind a URL
- [ ] Make the Model dashboard URL work with SSL
- [ ] Make `monitor.ersilia.io` (masked?) redirect to the dashboard URL.

### Documentation
NA

**Comment by DhanshreeA** [comment]
Hey @nicholas-kondal we're tracking all the stuff related to rolling out the tracking feature within Ersilia including integration with Splunk and the model inference pipeline. I'd really appreciate if you could put your review of the current code in the ersilia repo here, so that we can include it in our project plan. Thank you so much, we're super grateful for your work on this!

**Comment by nicholas-kondal** [comment]
Thanks @DhanshreeA, I've added my notes below:

**Context**
In the process of implementing metadata collection for the inference pipeline (see https://github.com/ersilia-os/model-inference-pipeline/issues/12 and https://github.com/ersilia-os/model-inference-pipeline/issues/14 for more details), the tracking module created by T4SG was explored as a way to integrate existing tracking functionality into the pipeline.

**Findings**
The tracking module is not currently being used by the inference pipeline and I would not recommend its use (in its current form) for the following reasons:

1. Multiple flags

There are two flags used for tracking, track_run (passed into the run command at [this line](https://github.com/ersilia-os/ersilia/pull/927/files#diff-a4b14323f1de6ed47571089c0bc8b1f24b290ae419510c9726910ff1db735974R46) and [this line](https://github.com/ersilia-os/ersilia/pull/927/files#diff-a4b14323f1de6ed47571089c0bc8b1f24b290ae419510c9726910ff1db735974R52)) and track_serve (passed into the serve command at [this line](https://github.com/ersilia-os/ersilia/pull/927/files#diff-bf2cb8d9ea55f818ef68bbb4c3ca35ea81e63f952c2277ca47eefd60b3b08b0eR68))

Since each flag is a boolean, this means that the tracking module can be in 4 different states, and the behaviours of every single state do not seem to have been accounted for in the module. It would be unwise to expect a user to understand which combination/s of flags will enable tracking. As such, they may never enable tracking in the first place. Ideally, there should only be one flag for ease of use and maintainability (or clear, well-documented reasons for requiring multiple flags).

2. Insufficient coverage

A model can be run by calling run() on its ErsiliaModel object directly or via the api CLI command, however the latter use case does not utilise the tracking module, thus the metrics for all model runs using the api command (which is used in the inference pipeline) would not be captured.

A review of all the ways a user could use the CLI to provide an input to a model and get back an output may be required so that the existing Ersilia code can be modified at the place which links all those different ways to easily add a connection to the tracking module and can be maintained regardless of any additions/removals/modifications of CLI commands or other unrelated parts of the codebase.

3. Unclear tracking context

In [https://github.com/ersilia-os/ersilia/pull/927/files#diff-bf2cb8d9ea55f818ef68bbb4c3ca35ea81e63f952c2277ca47eefd60b3b08b0eR24](url), it appears that the tracking is being done at the session level however, in other parts of the module, it is implied that tracking is being conducted at the model level and/or the run level. Given that (in the likely future), a session may contain more than one model, there could be some more clarity on the exact metrics that should be tracked and at what level, such as:
  - Session level: what model/s were used, how many runs were made, how long the session was, how many failures etc.
  - Model level: how many runs was a model used in, how many times did a model fail etc.
  - Run level: how long was the run, did it fail, what inputs were used etc.
  
4. Possible overlap with work being done on the inference pipeline

Apart from things like memory usage, most of the other metrics are ones that we would likely need to efficiently store and retrieve precalculations, so there may be work done as part of the inference pipeline which has similar functionality to the current tracking module but this could be developed in such a way that an external application like a dashboard can connect to the module as well.

**Comment by Malikbadmus** [comment]
@DhanshreeA , could I work on refactoring the code to resolve the duplication between the RunTracker and RunLogger classes?

**Comment by DhanshreeA** [comment]
> @DhanshreeA , could I work on refactoring the code to resolve the duplication between the RunTracker and RunLogger classes?

Sounds good @Malikbadmus, do you understand what you have to do here? Maybe you can provide a brief summary of how you'll approach this and I can open an issue and assign it to you. :)

**Comment by Malikbadmus** [comment]
@DhanshreeA, these are some of the solutions I have.

One of the examples I can see here is the instance method `log_results` and `log_meta` of the `RunLogger` class that logs the prediction outputs and the metadata of a model run. But this is already being duplicated in the 'track' instance method of the 'RunTracker` class which also performs a similar function.

Instead of having the tracking module create six (6) directories, and four (4) different files (Lake, metadata, logs, and current_session)  to be ingested, we can either do away with the lake and metadata files or refactor the track instance method to exclude Input and Result DataFrames, meta, and metadata.

We should also reroute the current_session file path to the ersilia_runs directory, it will make it easier to have all our output file in one location.

Overall we could maybe reduce the code redundancy by combining these two classes together, creating centralized activities for our work, it could also make debugging easier.

**Comment by dzumii** [comment]
@DhanshreeA I would like to work on removing multiple and redundant tracking flags. Thank you

**Comment by DhanshreeA** [comment]
Hey @dzumii you can start working on in a branch, and meanwhile I'll create an issue and assign you to it.

**Comment by dzumii** [comment]
> Hey @dzumii you can start working on in a branch, and meanwhile I'll create an issue and assign you to it.

Alright

**Comment by Malikbadmus** [comment]
Hi @DhanshreeA , I'd like to rework the code calculating memory usage - output and Docker container. Any suggestion from you will be really helpful. Many thanks.

**Comment by dzumii** [comment]
@DhanshreeA 
I would like to look into the reported bug about the tracking flag not working when an output.csv file is not specified

**Comment by DhanshreeA** [comment]
**Updates on Splunk dashboarding** based on the discussion with @miquelduranfrigola and @GemmaTuron 

    1. Current progress: We deconstructed the ersilia model TA app, and so far have the following questions, both related to the Splunk server setup, and the ersilia model TA:
        1. How are the views constructed? 
        2. Which elements can we reuse?
        3. What’s the look up table for?
        4. Why does the dashboard only have data from eos3b5e?
        5. Why was eos3b5e running on the server many months ago?
        6. What is bitsio?
        7. What’s portainer and why is it being used?
    2. Plan is to rewrite the whole app using reusable elements wherever possible.
    3. Another thing of importance is to map the directory structure in the way that the Splunk app expects (logs, lake, metadata, etc)

**Comment by miquelduranfrigola** [comment]
Thanks @DhanshreeA 

Let me answer a few questions:

- BitsIO is the company that helped us with the Ersilia Model TA app.
- Portainers is just a container manager installed in the server. We do not need to use it for anything.
- The look up table is to check which models are available.

In my opinion, it is not 100% important to reconstruct the full app. We need to build what is useful for us at this point (reusing if we can). So let's start really simple, by gathering straightforward metrics such as:

- [ ] Number of tracked rows
- [ ] Number of tracked models

Then we can make things more sophisticated, but I think we need an MVP with a minimalistic dashboard to start with.

**Comment by DhanshreeA** [comment]
I think I will close this issue since we have very well achieved this at this point except exposing the URL cleanly.
