### ISSUE TITLE
🐅 Epic: Remove BentoML as a dependency in Ersilia and move to FastAPI

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/ersilia#1137]
### Summary

We want to get rid of BentoML completely and use FastAPI to serve models. This will potentially help with: 

- the dependency hell we run into with BentoML when BentoML upgrades breaking backward compatibility
-  and in its current state Ersilia is not using BentoML to its full potential. 

### Objective(s)

- [x] Development of ersilia-pack to imitate bentoml's packing functionality (#1138)
- [x] Reworking eos-demo to reflect the new model template using a FastAPI app (#1139)
- [x] Ersilia CLI should have the necessary bindings for both the previous version using BentoML and the new version utilizing FastAPI (#1140)
- [x] Reworking the Dockerfile to build models because this would not require ersilia CLI and only ersilia-pack would be sufficient. (#1154)
- [x] Modifying the Docker build actions in CI to choose the correct Dockerfile based on the model (https://github.com/ersilia-os/eos-template/issues/67)

### Documentation

https://fastapi.tiangolo.com/
https://docs.google.com/presentation/d/1DTMkf7IYauIaZqwtiCd777wMWZXNQ9lnzCM4EqlUFnk/edit?usp=sharing

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA 

A lot of work has been done in that front. Please update this issue with all the changes and new features before closing it when it is complete.

**Comment by GemmaTuron** [comment]
Hello @DhanshreeA 

Please update this issue

**Comment by DhanshreeA** [comment]
Ersilia Pack has been a major feature that we have developed in the last couple of months. It mainly consists of three modules: linter, parser, and packer. This development has also lead to a new [eos-template](https://github.com/ersilia-os/eos-template) with notable changes being the introduction of an `install.yml`, file to specify model dependencies, and a `metadata.yml` file to specify model metadata. 

Ersilia Pack was designed to be a drop in replacement for BentoML bundles, such that Ersilia can simply build the said bundle, and spin up a model server from it. This is the core of the functionality addressed within the [`packer`](https://github.com/ersilia-os/ersilia-pack/blob/main/src/ersilia_pack/packer.py) module of ersilia pack. This module first creates the bundle structure to mimic the one created by bentoml, followed by creating the actual FastAPI app, creating an installation script to install the model's dependencies, and finally, writing any schema or status files as necessary.

With the aim of making Ersilia Pack as much backward compatible as possible, the [`parsers`](https://github.com/ersilia-os/ersilia-pack/blob/main/src/ersilia_pack/parsers.py) module has been designed to both parse models following the legacy structure and containing a Dockerfile declaring the model's dependencies, as well as models built from the new eos-template containing an install.yml file.

Ersilia codebase was modified to include distinct modules to handle fetching models that require [bentoml](https://github.com/ersilia-os/ersilia/blob/master/ersilia/hub/fetch/fetch_bentoml.py) vs models that can be built with [FastAPI](https://github.com/ersilia-os/ersilia/blob/master/ersilia/hub/fetch/fetch_fastapi.py). The way Ersilia distinguishes whether a model follows one or the other structure is by way of a [`TemplateResolver`](https://github.com/ersilia-os/ersilia/blob/c4c790a20a0e85f07b3f4e7603559e30caba67b2/ersilia/hub/fetch/actions/template_resolver.py) utility class. This class simply checks for the files expected in either formats (ie, `install.yml` for FastAPI based models, vs `pack.py`, or `Dockerfile` for bentoml based models). There is also [functionality](https://github.com/ersilia-os/ersilia/blob/c4c790a20a0e85f07b3f4e7603559e30caba67b2/ersilia/utils/paths.py#L140) for reading model metadata irrespective of whether it exists in `metadata.json`, or `metadata.yml` files.

Regarding [Dockerization](https://github.com/ersilia-os/ersilia/tree/master/dockerfiles/dockerize-ersiliapack) of models built using ersilia pack, we gain a massive advantage in building smaller images by building several base images, each for a different python version. This way, we only utilise the base image containing the Python version required by the model, and build on top of that. The script [`generate_all_dockerfiles`](https://github.com/ersilia-os/ersilia/blob/master/dockerfiles/dockerize-ersiliapack/base/generate_dockerfiles.py) gets utilised within the [workflow](https://github.com/ersilia-os/ersilia-pack/blob/744db859f3a0bf7a6ad7841a12442d762f6dbac1/.github/workflows/upload-ersiliapack-to-dockerhub.yml#L73) responsible for building these base images in the ersilia pack repo. In this way, we first [try to build](https://github.com/ersilia-os/eos-template/blob/main/.github/workflows/upload-model-to-dockerhub.yml) a model's Docker image usin Ersilia Pack, failing which, we resort to the bentoml approach [if the model follows that structure](https://github.com/ersilia-os/eos-template/blob/7b723fdeb3f1afde390c3692ecd6988362e5c986/.github/workflows/upload-bentoml.yml#L19).

**Comment by miquelduranfrigola** [comment]
Very good summary, thanks.
I think we can close this issue?

**Comment by GemmaTuron** [comment]
just a note to convert his nice explanation into a schema for the documentation
