### ISSUE TITLE
CONTRIBUTION PERIOD: MUSASIZI VICTORIA

### ISSUE THREAD

**Issue by musasizivictoria** [ersilia-os/ersilia#1277]
This issue will contain my weekly contribution progress towards Ersilia for easy tracking by the community mentors.

## WEEK 1 :  Get to know the community

- [x] # Task 1: Join in the communication channels

- [x] # Task 2: Install the Ersilia Model Hub

- [x] # Task 3: Motivation statement

- [ ] # Task 4: Obtain approval of the introductory tasks to continue contributing.

## Tasks completed

1. I was able to join the communication channel slack
2. I installed the Ersilia Model Hub. It was quite straight foward untill i obtained an error: on fetching the model 

![image](https://github.com/user-attachments/assets/b3b4028c-1d0b-4fcc-9450-36053fd3bb00)

The workaround was to uninstall isaura.

even when isaura would be good(especially for caching), i am not sure why its having compatibility details between Ersilia and Isaura the first time. I would need clarity here @Malikbadmus  if you can help.

![image](https://github.com/user-attachments/assets/f8ab786d-06c6-4949-bf19-070f76d1e7c7)

![image](https://github.com/user-attachments/assets/a7bfce8b-32db-4e3c-ac30-678b30f987e7)

![image](https://github.com/user-attachments/assets/618a45f9-af05-42fe-b747-40e7c5257e89)

Pulled a model image form docker hub

![ersilaia4](https://github.com/user-attachments/assets/188c54ea-a11b-4bf5-9dd2-9f5195e70940)

![ersilia](https://github.com/user-attachments/assets/ea917c6b-5e0c-4a51-a798-d24b48b43db0)

![ersilia2](https://github.com/user-attachments/assets/0d7b3839-f155-4aec-8c0c-6a0f0abb91e8)

![ersilaia3](https://github.com/user-attachments/assets/5acb48a0-2eb1-467c-81a9-3ef35df4a2e3)

3. Motivation statement
My name is Musasizi Victoria, I am so much thrilled to be accepted into the outreachy contribution phase and more especially joining Ersilia community. My history and passion aligns  well with the Vision of Ersilia; Aworld with Agilitaran access to healthcare. I  cant think less of this Vision. I come from a developing country where access to healthcare is like a mystery and given this movement in digital age, without a shadow of a doubt, access to healthcare will be very easy especially with the help of such a wonderful community of contributors  and master minders, that working together we can push the goals of the community while we make a global impact with my skills in Python, AI and ML. This is all that drives my passions to be part of this visionary community of like minded people. I am indebted to make this positive impact untill my country and all other countries around the globe have access to healthcare. This is my  pledge and motivation.

**Comment by GemmaTuron** [comment]
Hello @musasizivictoria 

We will keep track of Outreachy progress via Slack, please use this tool to communicate with mentors and send the motivation letter.
