### ISSUE TITLE
🐈 OUTREACHY CONTRIBUTION PERIOD: AJOKE YUSUF

### ISSUE THREAD

**Issue by Ajoke23** [ersilia-os/ersilia#1279]
### Summary

I opened this issue for the documentation of my progress during the Outreachy contribution period Winter 2024

### Objective(s)

WEEK 1
- [ ]  Join slack communication channel

- [ ] Install Ersilia Model Hub

- [ ] Motivation statement

- [ ] Obtain approval of the introductory tasks to continue contributing.

WEEK 2 & 3

- [ ]  Contribute to a good issue

WEEK 4

- [ ] Submit your final application.

**Comment by Ajoke23** [comment]
### **WEEK** 1: 
**Task 1**
- I joined the slack communication channel on 1st October , 2024. I further went to introduce myself in the #introduction channel which i introduced myself. My introduction can be found [here](https://ersilia-outreachy-w24.slack.com/archives/C07LXL4EUCA/p1727799343650439)
- Read Ersilia [code and conduct](https://github.com/ersilia-os/ersilia/blob/master/CODE_OF_CONDUCT.md)
- I have Ersilia Github page repository starred and forked. So, I checked out what Ersilia has been working on.

**Comment by GemmaTuron** [comment]
Hello @Ajoke23 

We will keep track of Outreachy progress via Slack, please use this tool to communicate with mentors and send the motivation letter. I will close this issue.
