### ISSUE TITLE
💡 Idea: Add Redis-Based Caching for Model API Results

### ISSUE THREAD

**Issue by Abellegese** [ersilia-os/ersilia#1470]
### **Description**

Currently, Erilia does not implement caching for API results produced by Ersilia models. As a result, running models frequently creates redundant computations and unnecessary resource expenditure, which is particularly challenging for users operating in low-resource environments or with resource-intensive models. 

To address this, we aim to integrate a Redis-based caching mechanism. Redis is a high-performance, lightweight, and widely-used in-memory database suitable for caching, especially given its compatibility with Docker. This new feature will allow results to be cached during each session, significantly reducing resource usage and improving user experience.

### **Implementation Design**
- **Redis Class Design**:
    1. **Async Implementation**: The Redis client will use an asynchronous interface for non-blocking operations to optimize performance, especially during high-concurrency scenarios.
    2. **Singleton Pattern**: A singleton ensures only one instance of the Redis client exists during runtime, avoiding resource waste and ensuring consistent access to the Redis cache.
    3. **Thread-Safe**: To safely handle multiple threads accessing the Redis client, thread safety will be prioritized, ensuring no unexpected behaviors occur.
    4. **Connection Pooling**: Connection pooling improves performance by reusing existing connections instead of creating new ones for each request, reducing overhead and latency.
- **High-level Mechanism**:  Each smiles will have a corresponding key that is perfect for caching. In each key the model id will be appended to cache smiles computation for each model. This will be implemented in the post function in both standard and conventional run. When we post first each smiles will be checked in the `redis` cache using `redis` high performance query function called `mget`. For the cached smiles their value will be returned and for non-cached smile, request will be made and their value will be cached for next time.

#### **Why This Is Needed**
Caching can significantly enhance performance by reducing duplicate computations. It also provides the following advantages:
- Improves speed for repeated API requests for the same inputs.
- Reduces server load, optimizing resources for intensive models.
- Enhances user experience, especially for users in constrained computing environments.

#### **Tasks**
- [x] Fetch and configure the Redis Docker image for development and testing.
- [x] Create the Redis client class that adheres to async, singleton, thread-safe, and connection pooling principles.
- [x] Integrate the Redis client into the **Standard API** and **Conventional Run** to handle caching for model results.
- [x] Add appropriate unit tests to ensure caching works as expected.
- [x] Update the API documentation to include caching behavior and configuration settings.
- [x] Create a troubleshooting section in the documentation for issues like Redis connection failure or unexpected cache behaviors.
- [x] Ensure the application gracefully handles cases where Redis is unavailable.

**Comment by miquelduranfrigola** [comment]
Thanks @Abellegese - let's make sure this does not overlap with the GDI work (i.e. inference store in AWS). This relates to local caching.

**Comment by Abellegese** [comment]
Okay @miquelduranfrigola , but I still don't have a clear view of their thier inner mechanism for their caching for me not to duplicate. Maybe we need time for this as well.

**Comment by miquelduranfrigola** [comment]
Sure, of course. Let's plan this well.

**Comment by DhanshreeA** [comment]
@Abellegese moving this to on-hold as well for the time being since we are working on other stuff right now. Let's come back to this next.

**Comment by Abellegese** [comment]
Yes @DhanshreeA we dont have time for that at the moment.

**Comment by DhanshreeA** [comment]
I am trying to reproduce this work, and I think there might be some files not committed to the branch, causing this error for example:

```python
Traceback (most recent call last):
  File "/home/dee/.pyenv/versions/ersilia-feature/bin/ersilia", line 5, in <module>
    from ersilia.cli import cli
  File "/home/dee/ersilia-project/ersilia-feature/ersilia/__init__.py", line 34, in <module>
    from .core.model import ErsiliaModel
  File "/home/dee/ersilia-project/ersilia-feature/ersilia/core/model.py", line 12, in <module>
    from ..serve.api import Api
  File "/home/dee/ersilia-project/ersilia-feature/ersilia/serve/api.py", line 17, in <module>
    from ..utils.cache import RedisClient
ModuleNotFoundError: No module named 'ersilia.utils.cache'
```
The feature is on this branch: `feature/integrating-redis-cache`

**Comment by DhanshreeA** [comment]
Per the current implementation, the cache is only stored within the Redis docker container, whereas we would want it to be volume mounted, and preferably without an implicit expiration period, unless the user requests one.

**Comment by DhanshreeA** [comment]
Here are the implementation considerations we will have to take into account for this solution:

1. We are still considering whether this should be an opt-in behavior or default with Ersilia.
2. We would need to call out system requirements and understand where we stand with that.
3. We should configure both an upper bound for the disk storage that Redis should be allowed to take up, in addition to configuring a default expiration period.
4. There should be a feature to review what we have cached in terms of inputs and models, beginning directly with input:model keys, ie, directly just the keys from the data store.
5. Finally, nowhere in the code should we refer to inputs as smiles, and should just refer to them as inputs.


The data model for this cache would look as follows:


Smi:CCC:Model:eos3b5e | {value: 44.096999999999994}
-- | --
Smi:CCC:Model:eos80ch | {        	"sexual_stage": 0.021725625633533144,        	"asexual_blood_stage": 0.6568954318505348    	}

**Comment by Abellegese** [comment]
This looks good @DhanshreeA

**Comment by GemmaTuron** [comment]
This is almost completely implemented. A few last changes to be done:

- Allow for a no-cache option at serve time (by default it will be cached)
- Do not send an error if Docker is not active, just a warning
- Limit the memory Redis can use

@Abellegese will implement those changes when possible and write some basic documentation on Redis

**Comment by Abellegese** [comment]
Thanks @GemmaTuron

**Comment by Abellegese** [comment]
# Redis Caching in Ersilia

Ersilia provides built-in caching using Redis to improve performance by storing model results. This caching system does not target variable outputs from generative models but instead caches various types of model outputs. The cache key is generated by creating an MD5 hash from the combination of the model ID and its input (e.g., SMILES string). it currently supports models which are packed using ersilia-pack server (a fastapi based model server).

---

## Caching Features

- **Automatic Caching**: By default, Ersilia caches model results.
- **Key Generation**: A unique key is created using an MD5 hash based on the model ID and input.
- **Flexibility**: Caching can be turned off during server startup if desired.

---

## How to Control Caching

When starting the Ersilia server, you can decide whether to use caching with these command-line options:

- **Enable or Disable Caching**:  
  To run with caching (default behavior):
  ```bash
  ersilia server eos3b5e --cache
  ```
  To run without caching:
  ```bash
  ersilia server eos3b5e --no-cache
  ```

---

## Memory Management

Redis manages its memory usage based on available system resources. By default, it uses **30% of the system RAM** for caching. You can adjust this limit by specifying a different memory usage fraction:

```bash
ersilia serve eos3b5e --max-cache-memory-frac <percent>
```

Simply replace `<percent>` with the desired percentage of your system's RAM that Redis should use.

---

## Redis Setup and Installation

Redis will be installed and set up automatically if all the following conditions are met:

1. **Docker is Installed**: Docker must be present on your system.
2. **Docker is Active**: Docker must be running.
3. **Caching is Enabled**: Caching should not be disabled via the command-line flag.

**Comment by Abellegese** [comment]
@GemmaTuron its good to close this issue after the documentation gets merged.

**Comment by GemmaTuron** [comment]
@Abellegese thanks! I'll merge the documentation into gitbook. If I want to check easily which data is cached, how would I go about it?

**Comment by Abellegese** [comment]
@GemmaTuron currently it does not support accessing the cached values as an independently from ersilia. What would be good I think is to create an endpoint in ersilia-pack to beautifully access all the cached data alone without any sort of computation. But the manual way to do this is just docker exec to the redis container and execute this
```bash
redis-cli SCAN 0
```

**Comment by Abellegese** [comment]
@GemmaTuron if the documentation is merged, better to close this up.
