### ISSUE TITLE
[Batch] Slack: Prompt Slack Users to Test New Model Submissions

### ISSUE THREAD

**Issue by D1M1TR10S** [ersilia-os/ersilia#479]
**Summary:** Prompt Slack users to test new submissions when they're posted to Slack.

**Comment by D1M1TR10S** [comment]
Some people on Slack don't have GitHub(50%), but many have both. It would be great if non-GitHub users could test the models too though.

**In GitHub:** Could create issues and assign them to a person within a team. Have a team of testers with GitHub collaborator status.

**Two audiences:**
- Internal team and testers – testing that things work in a diverse set of users and OSes.
- External users and scientists – testing more about usefulness and user experience. These users are accessing Ersilia via the CLI in the terminal.

**Comment by D1M1TR10S** [comment]
Start with Internal team/testers audience in GitHub. After that, we'll scale out to the wider audience of users/scientists.

Trigger event:
- After the model incorporating pipeline is finished (as soon as a model works and passes automated tests)
- Explicit trigger: At the end of the PR that passes all checks
- Create issue for review from @miquelduranfrigola or @GemmaTuron 

Manual task for trigger to be set off:
- @miquelduranfrigola or @GemmaTuron will add a label to the issue for it to be posted to Slack for review

Jobs:
- Create an issue and assign it to team member, which will post the new model to Slack for testing.

Use versioning as a trigger? (v0.01 for example) – perhaps in the future. No versioning now.

Current tempo: a few models every week. (10-15 or so every week at the most.)

**Comment by megamanics** [comment]
### Tasks
- [ ] Name of the team
- [ ] Create team
- [ ] Create Slack Channel
- [ ] Assign test members to Github Team
- [ ] Assign test members to Slack
- [ ] Add round robin assignment logic for team issues
- [ ] Add label `Slack` to repo
- [ ] Create Action / App based on `add label` to create an issue and assign to team repo
- [ ] Create Action / App to post new Issue created to the Slack channel

**Comment by GemmaTuron** [comment]
this is related to #478
