### ISSUE TITLE
[🐅 Epic]: Simultaneous serving of models

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#702]
## Request

At the moment, the `session.json` file only works with one model at a time. Whenever we are serving Ersilia models via DockerHub, then in principle multiple sessions could be allowed.

## Expected behaviour

- [x] If **at least** one of the served models is **not** served from docker, then send a warning and close all models served.
- [x] If all models served are `pulled_docker`, then multiple sessions are possible.
- [x] **Each terminal** should serve **one and only one** model. This is important to avoid unwanted mistakes from the user. Alternatively, we can allow for multiple runs in the same terminal if and only if the model_id is specified.

## Suggested solution

`session.json` could be a list, each element corresponding to one session.

**Comment by DhanshreeA** [comment]
Related to #1109

**Comment by GemmaTuron** [comment]
@DhanshreeA 

What is the status of this?

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA 
Is this on Queue or In Progress? What is the plan?

**Comment by DhanshreeA** [comment]
@GemmaTuron this has been implemented IS actually working exactly as expected now, re all the points within expected behavior section. I think we can close this. This is also related to #1197 (which I thought was a bug but it is not, as per the behavior defined here.)
