### ISSUE TITLE
[Internship Project]: Emmanuel Onwuegbusi

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ersilia#712]
### Summary

Hello,

This is a public issue for a virtual daily stand-up. We will use this to briefly share the tasks of the day and the challenges and advances made, so that we can ensure smooth support from the Ersilia mentors and alignment between daily tasks and overall internship goals.

### Scope

Initiative

### Objective(s)

Internship goals:

- Learn how to work in an Open Source Community
- Improve the infrastructure of the Ersilia Model Hub
- Improve the usability and platform compatibility of Ersilia Models, mainly via Docker Images
- Learn about AI/ML models for drug discovery
- Identify new relevant AI/ML models and datasets and add them to this [discussion](https://github.com/ersilia-os/ersilia/discussions/694)
- Incorporate new AI/ML models in the Hub
- Improve the documentation of the Ersilia Model Hub for users
- Improve the documentation of the Ersilia Model Hub for developers

### Team

| Role & Responsibility | Username(s) | 
|--|--|
| Intern | @emmakodes |
| Mentor| @leoank |
| Coordinator| @GemmaTuron  |

### Timeline

Before starting your work, line up a few tasks and short description. This should not take long. For example, it could be something like:
Wednesday 21st June
- [ ] Create Intern daily task tracker
- [ ] Update the Ersilia GitHub Project
- [ ] Make sure Git Actions start upon success of the other workflows
- [ ] Work on the documentation for model testing
- [ ] Attend the Drug Discovery intro by WCAIR

**Comment by GemmaTuron** [comment]
In this example, following the tasks of Wednesday 21st June:

- [x]  Create Intern daily task tracker
- [x]  Update the Ersilia GitHub Project
- [x]  Make sure Git Actions start upon success of the other workflows
- [ ]  Work on the documentation for model testing
- [x]  Attend the Drug Discovery intro by WCAIR

I have created all the templates for the Interns, spend a couple of hours revising the [GitHub Project](https://github.com/orgs/ersilia-os/projects/1) and updating the tasks. I have been working on identifying the bug in the GitActions, solved in this [issue](https://github.com/ersilia-os/eos-template/issues/29).
I have set a meeting with @miquelduranfrigola to discuss in detail his comments on the [Model testing discussion](https://github.com/ersilia-os/ersilia/discussions/700) but I haven't been able to start writing yet, i am to do so by the end of the week.
Looking forward to the WCAIR next lesson!

Pro tip: adding the links to the issues and discussions you mention will be very helpful!

**Comment by GemmaTuron** [comment]
Hi @emmakodes,
Please make use of this issue to report your daily tasks so we can keep track of the work.

**Comment by emmakodes** [comment]
Thanks @GemmaTuron

**Comment by emmakodes** [comment]
### Wednesday 21st June:

- [x ] Tested model eos9ei3 using CLI and Docker: https://github.com/ersilia-os/eos9ei3/issues/6
- [x] Tested model eos9yy1 using CLI and Colab: https://github.com/ersilia-os/eos9yy1/issues/14

- [x] Reinstalled ersilia test to model eos9tyg https://github.com/ersilia-os/eos9tyg/issues/4
- [x] Attended the Drug Discovery Intro course session

**Comment by emmakodes** [comment]
### Thursday 22nd June
- [ ] Clean UP & Dockerization eos22io https://github.com/ersilia-os/eos22io/issues/5
- [ ] Test model eos9ei3 on Colab since it failed the first time https://github.com/ersilia-os/eos9ei3/issues/6

**Comment by emmakodes** [comment]
> ### Thursday 22nd June
> * [ ]  Clean UP & Dockerization eos22io [Clean UP & Dockerization eos22io eos22io#5](https://github.com/ersilia-os/eos22io/issues/5)
> * [x]  Test model eos9ei3 on Colab since it failed the first time [New model ready for testing! eos9ei3#6](https://github.com/ersilia-os/eos9ei3/issues/6)
> * [ ]  Clean UP & Dockerization eos1af5 [Clean UP & Dockerization eos1af5 eos1af5#1](https://github.com/ersilia-os/eos1af5/issues/1)
> * [x]  Attend lab meeting

I need a review on [Clean Up & Dockerization eos22io](https://github.com/ersilia-os/eos22io/issues/5) to know the next action to take

**Comment by GemmaTuron** [comment]
I've merged the PR on eos22io, if it passes all the checks then I'll assign the model for testing and we'll be done with it

**Comment by emmakodes** [comment]
> I've merged the PR on eos22io, if it passes all the checks then I'll assign the model for testing and we'll be done with it

It passes all the tests and it builds for only linux/AMD64

**Comment by emmakodes** [comment]
### Friday 23rd June
- [x] Finish Up Clean UP & Dockerization of eos22io and make pull request https://github.com/ersilia-os/eos22io/issues/5
- [x] Test model eos526j from source code and CLI https://github.com/ersilia-os/eos526j/issues/4
- [ ] Clean UP & Dockerization eos1af5 https://github.com/ersilia-os/eos1af5/issues/1 (Partly done)

**Comment by emmakodes** [comment]
### Monday 26th June
- [ ] Clean UP & Dockerization eos1af5 https://github.com/ersilia-os/eos1af5/issues/1 
Hello @GemmaTuron I noticed you assigned Febie eos1af5 model now.

**Comment by GemmaTuron** [comment]
Hi @emmakodes 

I've assigned a new model, sorry!
Are you done with the testing of all models assigned to you as well?

**Comment by emmakodes** [comment]
H

> Hi @emmakodes
> 
> I've assigned a new model, sorry! Are you done with the testing of all models assigned to you as well?

Hello @GemmaTuron I'm still in the loop of testing model eos526j

**Comment by emmakodes** [comment]
### Continuation Monday 26th June
- [x] Test model eos65rt https://github.com/ersilia-os/eos65rt/issues/8
- [x] Test model eos7pw8 https://github.com/ersilia-os/eos7pw8/issues/9
- [ ] Clean UP & Dockerization eos4zfy https://github.com/ersilia-os/eos1af5/issues/1
- [x] Attend meeting with @leoank

**Comment by emmakodes** [comment]
Tuesday 27th June
- [ ] Clean UP & Dockerization eos4zfy https://github.com/ersilia-os/eos1af5/issues/1
- [ ] Re-Test model eos65rt if issue has been fixed https://github.com/ersilia-os/eos65rt/issues/8
- [ ] Attend meeting

**Comment by emmakodes** [comment]
Wednesday 28th June
- [x] Clean UP & Dockerization of eos4zfy https://github.com/ersilia-os/eos4zfy
- [x] Test model eos97yu https://github.com/ersilia-os/eos97yu/issues/7
- [x] Attend the Drug Discovery Intro course session by WCAIR

**Comment by emmakodes** [comment]
### Thursday 29th June
- [ ] Test model eos7pw8 https://github.com/ersilia-os/eos7pw8/issues/9

**Comment by GemmaTuron** [comment]
Hi @emmakodes

Great, I have assigned two more models!

**Comment by emmakodes** [comment]
Friday 30th June
Wednesday 28th June
- [ ] Clean UP & Dockerization eos3cf4 https://github.com/ersilia-os/eos3cf4/issues/4
- [x] Re-Test model eos7pw8 https://github.com/ersilia-os/eos7pw8/issues/9

**Comment by emmakodes** [comment]
Monday 3rd July
- [ ] Attend meeting with @leoank 
- [ ] Attend Ersilia containers and environments meeting

**Comment by GemmaTuron** [comment]
Hi @emmakodes 

Check my comment on eos7pw8 and investigate what can be happening, we will talk about it on the meeting today. Please also revise the eos3cf4 and the new model I've assigned to you if you finish all the previous work

**Comment by emmakodes** [comment]
Okay @GemmaTuron

**Comment by emmakodes** [comment]
Tuesday 4th July

- [ ] Test model eos7pw8 https://github.com/ersilia-os/eos7pw8/issues/9
- [ ]  Work on issues concerning eos3cf4 https://github.com/ersilia-os/eos3cf4/issues/3
- [ ] Clean UP & Dockerization eos7jio https://github.com/ersilia-os/eos7jio/issues/5
- [ ]  Test model eos6pbf https://github.com/ersilia-os/eos6pbf/issues/2

**Comment by GemmaTuron** [comment]
Hi @emmakodes 

Let's focus on eos3cf4 first and then the others. If you can coordinate with @samuelmaina regarding eos7pw8 great

**Comment by emmakodes** [comment]
Wednesday 5th July
- [ ] Clean UP & Dockerization eos7jio https://github.com/ersilia-os/eos7jio/issues/5
- [x]  Test model eos6pbf https://github.com/ersilia-os/eos6pbf/issues/2
- [x] Attend lab meeting

**Comment by emmakodes** [comment]
Thursday 6th July
- [ ]  Test model eos2rd8 https://github.com/ersilia-os/eos2rd8/issues/1

**Comment by GemmaTuron** [comment]
@emmakodes 

I've assigned new models!

**Comment by emmakodes** [comment]
Friday 7th July
- [ ] Test model eos7pw8
- [ ]  Test model eos2rd8 https://github.com/ersilia-os/eos2rd8/issues/1
- [ ] Clean UP & Dockerization of eos7w6n https://github.com/ersilia-os/eos7w6n/issues/5

**Comment by emmakodes** [comment]
Monday 10th July
- [ ] Clean UP & Dockerization of eos7w6n https://github.com/ersilia-os/eos7w6n/issues/5
- [ ]  Test model eos7nno https://github.com/ersilia-os/eos7nno/issues/2
- [ ] Do Docker Testing for eos8h6g

**Comment by emmakodes** [comment]
Tuesday 11th July
- [ ]  Test model eos1amr
- [ ] Test model eos6m4j
- [ ] Test model eos1af5
- [ ] check why issue creation is skipped with eos1af5 model
- [ ] Clean UP & Dockerization of eos7w6n  [ I wrote the challenge with this model here: [issue](https://github.com/ersilia-os/eos7w6n/issues/5)]

**Comment by emmakodes** [comment]
Wednesday 12th July
- [ ] Test model eos6m4j
- [ ] Clean UP & Dockerization eos4cxk https://github.com/ersilia-os/eos4cxk/issues/5

**Comment by GemmaTuron** [comment]
Thanks for the update @emmakodes 

we still need to look into the issue with model `eos526j` with @miquelduranfrigola 
Meanwhile I'll assign some new models for refactoring so you can go ahead

**Comment by emmakodes** [comment]
Okay @GemmaTuron

**Comment by emmakodes** [comment]
Thursday 13th July
- [ ] Clean UP & Dockerization eos8c0o https://github.com/ersilia-os/eos8c0o/issues/3
- [ ] Test model https://github.com/ersilia-os/eos7a04/issues/8
- [ ] Test model eos6m4j
- [ ] Test model eos526j

**Comment by GemmaTuron** [comment]
Hi @emmakodes !

Good job in the refactoring! Please complete the model testing so we can close the open issues, and then move onto the new models I've assigned to you

**Comment by emmakodes** [comment]
Friday 14th July
- [x] Test model eos7a04 https://github.com/ersilia-os/eos7a04/issues/8
- [ ] Test model eos526j
- [ ] Clean UP & Dockerization eos77w8 https://github.com/ersilia-os/eos77w8/issues/4
- [ ] Clean UP & Dockerization eos2ta5 https://github.com/ersilia-os/eos2ta5/issues/1

**Comment by emmakodes** [comment]
Monday 17th July
- [ ] Clean UP & Dockerization eos77w8 https://github.com/ersilia-os/eos77w8/issues/4
- [ ] Clean UP & Dockerization eos2ta5 https://github.com/ersilia-os/eos2ta5/issues/1
- [ ] Test model eos93h2 https://github.com/ersilia-os/eos93h2/issues/6
- [ ] Test model eos4tcc https://github.com/ersilia-os/eos4tcc/issues/2
- [ ] Retest eos1amr https://github.com/ersilia-os/eos1amr/issues/4
- [ ] check if `Libxrender` package is installed system-wide to investigate `ImportError: libXrender.so.1: cannot open shared object file: No such file or directory` error when I fetch eos526j model via github

**Comment by emmakodes** [comment]
Wednesday 19th July
- [ ] Clean UP & Dockerization eos157v https://github.com/ersilia-os/eos157v/issues/1
- [ ] Clean UP & Dockerization eos2mhp https://github.com/ersilia-os/eos2mhp/issues/1
- [ ] Still study why `Model Test on push` workflow for eos77w8 model is stopping at `Install Ersilia` step  https://github.com/ersilia-os/eos77w8/actions/runs/5590584224

**Comment by emmakodes** [comment]
Thursday 19th July
- [x] Clean UP & Dockerization eos2mhp https://github.com/ersilia-os/eos2mhp/issues/1
- [x] Attend weekly lab meeting

**Comment by emmakodes** [comment]
Friday 21st July
- [ ] Open PR for eos157v and eos2mhp models
- [ ] Work on `libxrender` install for eos526j
- [ ] delete `ersilia.json` file for eos77w8 model since it may not be needed for anything and open a PR

**Comment by GemmaTuron** [comment]
Hi @emmakodes 

I haven't seen the PR on eos77w8, could you open it? Also eos157v and eos2mhp do not have PRs. I won't assign new tasks until these are completed

**Comment by emmakodes** [comment]
Tuesday 25th July
- [x] Open PR for eos157v and eos2mhp models
- [x] delete `ersilia.json` file for eos77w8 model since it may not be needed for anything and open a PR 
- [x] Attend Meeting

**Comment by emmakodes** [comment]
Wednesday 26th July
- [x] Try to research ways to make runners use `Python3.10.10` as the installed Python
- [ ] Clean UP & Dockerization eos3ae7 https://github.com/ersilia-os/eos3ae7/issues/1

**Comment by emmakodes** [comment]
Thursday 27th July
- [ ] Clean UP & Dockerization eos3ae7 https://github.com/ersilia-os/eos3ae7/issues/1
Continue with eos3ae7 and try to resolve the dependency conflict in the model and find the right packages for eos3ae7
- [ ] attend lab meeting

**Comment by emmakodes** [comment]
Friday 28th July
- [x] Test model eos93h2
- [x] retest model eos526j
- [ ] Clean UP & Dockerization eos3ae7 https://github.com/ersilia-os/eos3ae7/issues/1
- [ ] Clean UP & Dockerization eos5ecc https://github.com/ersilia-os/eos5ecc/issues/2

**Comment by emmakodes** [comment]
Monday 31st July
- [ ] Clean UP & Dockerization eos3ae7 https://github.com/ersilia-os/eos3ae7/issues/1
(Resolve iteration issue for eos3ae7 and debug ersilia not getting the generated molecules)
- [ ] Clean UP & Dockerization eos5ecc https://github.com/ersilia-os/eos5ecc/issues/2
- [ ] Brainstorm ways to integrate the local workflow tests in the pipeline

**Comment by emmakodes** [comment]
Tuesday 1st Auguust
- [ ] Retest eos1amr
- [ ] Test model eos3xip
- [ ] Test model eos8a5g
- [ ] Open PR to add `libxrender` dependency to eos526j
- [ ] Test eos7pw8
- [ ] Test eos8451
- [ ] Clean UP & Dockerization eos3ae7
- [ ] Clean UP & Dockerization eos5ecc
- [ ] Attend meeting
- [ ] prepare my slide for tomorrow meeting
- [ ] attend meeting with Ank

**Comment by GemmaTuron** [comment]
Hi @emmakodes 

You have a ling list of tasks, if you don't manage to tackle them all by today it is fine, if I was you i'd prioritize as follows:
- Model Testing so we can close open issues
- Prepare meetings
- Refactor model eos3ae7
- eos5ecc needs modifications on the Ersilia code base, so that would be the last thing to tackle, probably not today

**Comment by emmakodes** [comment]
Okay, @GemmaTuron thanks, let me follow your procedure. I appreciate

**Comment by emmakodes** [comment]
Monday 7th August
- [ ] Retest eos8451
- [ ] Clean UP & Dockerization eos3ae7 ( Hello @GemmaTuron I am waiting on your comment for [this](https://github.com/ersilia-os/eos3ae7/issues/1#issuecomment-1665633577) )
- [ ] work on the script to build images of models locally

**Comment by GemmaTuron** [comment]
Thanks @emmakodes 

Is there any other model pending on your list aside from the ones mentioned here?

**Comment by GemmaTuron** [comment]
Hi @emmakodes 

Revise no further model testing is assigned to you, if it is please complete it as well.
Also, could you try out the model test developed by Riley and febie and provide feedback on the Slack channel?

**Comment by emmakodes** [comment]
Sure @GemmaTuron I will test it out. I am trying to complete the model testing I have left.

**Comment by emmakodes** [comment]
Thursday 10th August
- [ ] Test the test module developed by Riley and Febie
- [ ] work on the script for the local build of docker of images

**Comment by GemmaTuron** [comment]
Hi @emmakodes 

If the work on model refactoring and testing is finished, let's focus on the local build of Docker images. How is that going?

**Comment by emmakodes** [comment]
14th August
- [ ] Work on the script for the local build of docker of images
Currently, I am focused on resolving this [issue](https://github.com/ersilia-os/ersilia/issues/760) as it relates to the local build of docker images of models.

**Comment by GemmaTuron** [comment]
Hi @emmakodes !

It was great to work with you, thanks so much for your contributions to Ersilia, we hoped you learnt and enjoyed as much as we did! Please, remain engaged with the community and feel free to open any issues or contribute to open ones :)
I'll now close this issue as completed !
