### ISSUE TITLE
✍️ Contribution period: Zaha Fatima

### ISSUE THREAD

**Issue by zaha-fdzs** [ersilia-os/ersilia#844]
### Week 1 - Get to know the community

- [x] Join the communication channels
- [x] Open a GitHub issue (this one!)
- [x] Install the Ersilia Model Hub and test the simplest model
- [x] Write a motivation statement to work at Ersilia
- [x] Submit your first contribution to the Outreachy site

### Week 2 - Install and run an ML model

- [x] Select a model from the suggested list
- [x] Install the model in your system
- [ ] Run predictions for the EML
- [ ] Compare results with the Ersilia Model Hub implementation!
- [ ] Install and run Docker!

### Week 3 - Propose new models

- [ ] Suggest a new model and document it (1)
- [ ] Suggest a new model and document it (2)
- [ ] Suggest a new model and document it (3)

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by DhanshreeA** [comment]
Hi @zaha-fdzs I see some items from week 1 are pending, please let us know how we can support you in completing them.

**Comment by zaha-fdzs** [comment]
Hello @DhanshreeA, I really appreciate you checking in! 

I have now successfully installed Ersilia, and have also successfully tested the simplest model.

**Comment by zaha-fdzs** [comment]
### **MOTIVATION LETTER**

Warm greetings to mentors of Ersilia Model Hub project and fellow Outreachy applicants! I am Zaha Fatima, a Biomedical Engineer who recently graduated from NED University of Engineering and Technology, Karachi, Pakistan. I really enjoy programming - Python language is my favourite! - and I am always looking to contribute to projects that work on improving Public Health and the quality of lives of people impacted with medical struggles. Over the course of my academic journey, I have developed a good grasp on Python language and Bash, having used them in various university and hobby projects.

I am excited - and READY - to contribute to the Ersilia Model Hub project! I have good understanding of simple Machine Learning algorithms and the math behind them. My experience with implementing Machine Learning models include practicing ML algorithms on public datasets like cell_sample.csv on Kaggle, and working on a university course project wherein I implemented ML models using Python on EEG data processed using EEGLAB to determine effects of a non-invasive neurofeedback program. I also studied about AlphaFold2 and OpenFold when they were released during my clinical research internship in a hospital in 2021; I was working on Next Generation Sequencing (NGS) data analysis, and my team was working on predicting protein structure of sequenced transcripts. I remember realizing just how impactful machine learning is, and can be, in improving our understanding of diseases and creating better healthcare.

I am looking forward to using my skills in Python programming, Conda and Bash for a wonderful project like Ersilia. The philosophy of Open Source and FOSS is really meaningful to me, and I am happy to be starting my journey in such an active and cooperative community.

Within this Outreachy Contribution Period, I aim to learn how to:

1. Successfully use Docker; 
2. Successfully implement third party codes of ML models;
3. Work with different dependencies and environments; 
4. Successfully run predictions for Essential Medicines List (EML);
5. Successfully run models in Ersilia Model Hub by understanding Ersilia's backend; and 
6. Search literature and learn a whole lot more about Machine Learning models that can help improve research on infectious and neglected diseases. 

Seeing how collaborative fellow applicants are and supportive mentors are, I feel really motivated to use this opportunity to the best of my ability! I also hope I can prove to be helpful to others in their open source journey as well :)

**Comment by zaha-fdzs** [comment]
### Progress Report of 📆 WEEK 1: Get to know the community

**TASKS 1 and 2: Joining Slack and Opening a GitHub Issue**

In the first week of the Outreachy Contribution period, I joined in the communication channel on Slack, introduced myself, learned about fellow Outreachy applicants and Ersilia mentors, and opened my first-ever issue on GitHub!

I am so inspired by the promptness with which mentors and fellow applicants communicate and solve issues - I am learning a lot!

**TASK 3: Installing Ersilia**

I installed Ersilia on my PC running Ubuntu 18.04 OS and tested the simplest model successfully as outlined in the Ersilia Gitbook.

**TASKS 4 and 5: Motivation Statement and Opening an Application to Ersilia**

After spending this week learning about Ersilia and its goals, exploring the Ersilia Model Hub and engaging with the mentors on the first community call, I felt ready and excited to start contributing to the Ersilia Model Hub Project! 

I wrote my motivation statement outlining why I am interested in working at Ersilia and commented it here in my issue.

I also submitted my first Outreachy contribution linking this GitHub issue.

**Comment by HellenNamulinda** [comment]
Hello @zaha-fdzs, thank you for completing week 1 tasks.
We see you are yet to complete week 2 tasks. 
You ticked that you Installed the model in your system. Which model did you choose to work with?
Please let us know how we can help you so you can progress to week 3 tasks.

**Comment by GemmaTuron** [comment]
Hello,

Thanks for your work during the Outreachy contribution period, we hope you enjoyed it! We will now close this issue while we work on the selection of interns. Thanks again!
