### ISSUE TITLE
[🐅 Epic]: Ersilia Model Hub Maintenance: background and first steps

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ersilia#977]
# Background

This is the opening issue of the project [Ersilia Automation Workflow Module](https://docs.google.com/document/d/1dT5ymG8OkxMJ4EbquxLpDpe5bAQ8sAL9/edit?usp=sharing&ouid=114775674178390159004&rtpof=true&sd=true) done in collaboration with [Harvard Tech For Social Good](https://socialgood.hcs.harvard.edu/) (T4SG). The goal is to create suite of GitHub Actions workflows and a Python-based CLI testing module that run several critical monitoring and maintenance tasks for the [Ersilia Model Hub](https://github.com/ersilia-os/ersilia).

* @DhanshreeA and @miquelduranfrigola will be supervising the project from Ersilia's end.
* The main working repository will be [Ersilia Maintenance](https://github.com/ersilia-os/ersilia-maintenance). The [Ersilia CLI](https://github.com/ersilia-os/ersilia) will also be modified.

# Useful resources

To become familiar with the Ersilia Model Hub, these resources can be helpful:
* [Ersilia Book](https://ersilia.gitbook.io): The main documentation of Ersilia can be found in this page.
* [Model contribution pipeline video](https://youtu.be/I7dYI4ZF7Q0?si=CdogDgZum28B6ugj): This recording made by @Lehcar shows how to contribute a model to Ersilia. While model contribution is not the scope of the project, this helps understand the origin of the models.
* [Model catalog in AirTable](https://airtable.com/appgxpCzCDNyGjWc8/shrNc3sTtTA3QeEZu): This spreadsheet shows the current catalog of models, along with their status and metadata.
* [Ersilia Issues](https://github.com/ersilia-os/ersilia/issues): Participating in issue discussions is a great way of becoming familiar with the tool.

# First steps

To get started with the project, we need to:

## Set up users.
- [x] Include T4SG volunteers as collaborators/members to the Ersilia GitHub org. @miquelduranfrigola will create a `t4sg` team in Ersilia.
- [x] Give permissions to submit to the `main` branch of the [ersilia-maintenance](https://github.com/ersilia-os/ersilia-maintenance) repository. @miquelduranfrigola will do it.

## Work on a case example on the Ersilia CLI

In the Ersilia CLI, we have a `ModelTester` class that we did not manage to bring to production yet. It can be found [here](https://github.com/ersilia-os/ersilia/blob/master/ersilia/publish/test.py). In my opinion, we should write an independent script in the context of this project, containing its own evaluator or tester class - the current `ModelTester` is too involved to get started with. If you agree, let's:

- [x] Create a script (`/publish/inpect.py`) containing a main class called `ModelInspector` (feel free to change naming).
- [x] To get started, let's have a method in this class that checks whether a given model repository exists in GitHub. For example, this input should return `True`: `"eos3b5e"` since the URL https://github.com/ersilia-os/eos3b5e is valid, while `"eos9xyz"` does not lead to a valid URL https://github.com/ersilia-os/eos9xyz.
- [x] Let's include the `ModelInspector` class as part of the CLI commands. You can find out how commands are written in Ersilia by browsing [other examples](https://github.com/ersilia-os/ersilia/tree/master/ersilia/cli). I would say that, for now, we can create a command that works like this: `ersilia inspect eos3b5e` and returns a JSON string or file, in this case something like `{'is_github_url_available': 'True'}`. (@DhanshreeA - we may want to eventually merge the `inspect` and `test` commands, but for now I would keep it separate to simplify the project).

## Implement an automation on the Ersilia Maintenance repository

Following this first example, we should create a GitHub Actions workflow that:
- [x] Is triggered on a scheduled basis. For example, every midnight. Examples of how this can be done can be found in the [Ersilia Stats](https://github.com/ersilia-os/ersilia-stats) repository. I recommend that a `workflow_dispatch` trigger is also added.
- [x] Installs the Ersilia CLI. Many examples on how to install the Ersilia CLI in a workflow can be found [here](https://github.com/ersilia-os/ersilia/tree/master/.github/workflows).
- [ ] Eventually, we'll want this action to work on any model, but for now, let's assume we just work on `eos3b5e`. Therefore, the action should run something like `ersilia inspect eos3b5e > inspect_output.json`. We can also try if for `eos9xyz`.
- [ ] Finally, an issue should be automatically created in the repository if the `is_github_url_available` field is `False`. In this example, an issue would be created for `eos9xyz` but not for `eos3b5e`.

# Next steps

As soon as we have finished with this first steps, we will:
1. Decide other checks we may want to do on the models, increasing the complexity of the checks.
2. Define a good scheduling system to inspect all models in the Ersilia Model Hub in a periodic manner.

**Comment by miquelduranfrigola** [comment]
The following relevant questions were raised by the team. I try to respond:

#### What is the difference between writing a .py script and a .yml script? Does each .yml file need to import a python file?
The way I envisage this is as follows (but I am open to discussion!):
1. The python files will reside inside the Ersilia CLI codebase. Ultimately, they can be run via the `ersilia inspect` command as described above.
2. Therefore, in the .yml file of the github action, the first thing that needs to happen is that Ersilia is installed. Then, in a next step within the action, we can execute the `ersilia inspect` command.
In sum, I see the .yml file as a workflow for running several steps (e.g. install ersilia, inspect model, etc.). In this project, we'll have to work both on .py and .yml files.

#### Also, do you see us cloning the repository and writing up the files in a code editor, like VSCode? Or should there be a "run" option on the github Actions page on github itself?
I would definitely work on VSCode. By consensus, worflow files are stored in `.github/workflows/`, so if you write them in VSCode and push changes, they will be reflected in the GitHub web interface.

#### Also, we create the .yml file inside of the ersilia-os/ersilia-maintenance folder correct?
Yes, you can create it in the `ersilia-os/ersilia-maintenance/.github/workflows` folder

**Comment by anshikavashistha** [comment]
May I work on this issue @miquelduranfrigola as I am a beginner in Ersilia and would love to work in this issue?

**Comment by miquelduranfrigola** [comment]
Hello @anshikavashistha, thanks for your message. This work is led by a team of volunteers from Harvard T4SG, so we are well covered for now! We'll let you know if we need assistance.

**Comment by anshikavashistha** [comment]
No problem @miquelduranfrigola 
Please let me know if you need any kind of assistance

**Comment by miquelduranfrigola** [comment]
Hello @ersilia-os/harvard-t4sg 

The first version of the workflow works! https://github.com/ersilia-os/ersilia-maintenance/actions/runs/8382908764/job/22957612010

There are just a few things to finalize related to this PoC. Please see [this issue](https://github.com/ersilia-os/ersilia-maintenance/issues/1) for more.

**Comment by DhanshreeA** [comment]
After inspecting the contents of the diff between the two repositories, the only files we need to keep are the following:

- [ersilia/cli/commands/inpsect.py](https://github.com/reneeperpignan/ersilia-r/blob/master/ersilia/cli/commands/inspect.py) to implement the inspect command.
- [ersilia/publish/inspect.py](https://github.com/reneeperpignan/ersilia-r/blob/master/ersilia/publish/inspect.py) which implements the `ModelInspector` class. 
- Finally we need to copy the following [block](https://github.com/reneeperpignan/ersilia-r/blob/0a223005ddde01ae6df6d82dd25bdf011bbdde73/ersilia/cli/cmd.py#L76) in ersilia/cli/cmd.py to actually register the inspect command within the ersilia cli. 

Please make sure to remove all `print` calls and replace them with debug logs. 
@dzumii do you think you'd be able to take this up?

**Comment by dzumii** [comment]
Ok, I will check it out @DhanshreeA

**Comment by GemmaTuron** [comment]
Hi @DhanshreeA 

You merged @dzumii 's code. Can you please update on the status of this issue?

**Comment by DhanshreeA** [comment]
@GemmaTuron this is good to close now, thanks!
