### ISSUE TITLE
✍️ Contribution period: <Malik Badmus> 

### ISSUE THREAD

**Issue by Malikbadmus** [ersilia-os/ersilia#979]
### Week 1 - Get to know the community

- [ ] Join the communication channels
- [ ] Open a GitHub issue (this one!)
- [ ] Install the Ersilia Model Hub and test the simplest model
- [ ] Install Docker if needed, and test another model
- [ ] Write a motivation statement to work at Ersilia
- [ ] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [ ] Select a model from the list suggested in GitBook
- [ ] Download and serve the model via the Ersilia Model Hub to ensure it works
- [ ] Open a repository on your GitHub user with all the necessary files
- [ ] Select and clean a dataset of 1000 molecules (example notebook 1)
- [ ] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [ ] Find a suitable dataset with sufficient experimental results
- [ ] Clean and standardize the dataset
- [ ] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by Malikbadmus** [comment]
Encountered a bug during installation, but it has been resolved.

Details are available here #976

**Comment by Malikbadmus** [comment]
To show the installation was successful the fetch and serve command was executed on model `eos3b5e`  then I ran a prediction on a SMILES string "CCCC" .

![Sucess](https://github.com/ersilia-os/ersilia/assets/46167222/87f6590c-4496-43ff-ac42-db17116f4e28)

**Comment by Malikbadmus** [comment]
I have Docker already installed, Successfully downloaded the latest `ersiliaos/eos4wt0` image.

![success2](https://github.com/ersilia-os/ersilia/assets/46167222/c013aca6-45e5-4917-84e6-0f2fe1919136)

**Comment by Malikbadmus** [comment]
@GemmaTuron, I think the issue is probably with the model `eos4wt0`. 

Because I was able to docker pull, serve and predict another model `eos3b5e` successfully.

![success3](https://github.com/ersilia-os/ersilia/assets/46167222/6196214e-108c-4934-aa1f-0c7e1c7d999e)

**Comment by Ajoke23** [comment]
> @GemmaTuron, I think JSON decoder is having an issue with parsing some packages in this model `eos4wt0`. 
> 
> Because I was able to docker pull, serve and predict another model `eos3b5e` successfully.
> 
> ![success3](https://github.com/ersilia-os/ersilia/assets/46167222/6196214e-108c-4934-aa1f-0c7e1c7d999e)
> 

@Malikbadmus I was thinking the issue will be concerning the previous model you try serving. Since this work, then I think there is an issue with the model server JSON format.
I'll try to run it from my end and give you a feedback

**Comment by Ajoke23** [comment]
> I have Docker already installed, Successfully pulled the latest `ersiliaos/eos4wt0` image from the DockerHub.
> 
> ![success2](https://github.com/ersilia-os/ersilia/assets/46167222/c013aca6-45e5-4917-84e6-0f2fe1919136)
> 
> Though i ran into a `JSONDecodeError` while trying to serve the model
> 
> ### Describe the steps to reproduce the behavior.
> 
> `ersilia serve eos4wt0 > Errorr.log 2>&1`
> 
> ### Expected behavior.
> 
> Model served successfully with a list of API keys to run predictions
> 
> ### Error Log.
> 
> [Errorr.log](https://github.com/ersilia-os/ersilia/files/14497158/Errorr.log)
> 
> ### Operating environment.
> 
> Ubuntu 22.04.1

@Malikbadmus Let me try to run this particular model, if I also get the same error then it'll most likely the model.
That's aside, ensure that you're using the latest version of Ersilia tool and the dependencies

**Comment by Malikbadmus** [comment]
Many thanks @Ajoke23 , were you successful in fetching the model through the Docker hub?

**Comment by GemmaTuron** [comment]
Hi @Malikbadmus @Ajoke23 

Let me tag here @DhanshreeA so she can have a look

**Comment by Ajoke23** [comment]
> Many thanks @Ajoke23 , were you successful in fetching the model through the Docker hub?

Yes, I was.

Have you been able to solve the problem. Did you see my suggestion on slack?
Did it help debug the error?

**Comment by Malikbadmus** [comment]
@Ajoke23 , the command suggestion you gave is to fetch the log of a container named eos4wt0?

@DhanshreeA , this is the error log file.


Looking through it, it has to do with betoml serve fail

> Error: bentoml-cli info failed: BentoService eos4wt0:20240305145303 not found - NOT_FOUND:BentoService `eos4wt0:20240305145303` is not found

**Comment by DhanshreeA** [comment]
Ah @Malikbadmus if you run into this particular issue with BentoService not being found, I would recommend pruning your current docker images with `docker system prune -a`. We recently introduced a new way to build model images in Ersilia and it might be the case that the image you have is using a previously cached layer. Let me know if it works after you prune your docker stuff.

**Comment by Malikbadmus** [comment]
Many thanks @DhanshreeA , it looks like the cached layers were causing conflict with the recent changes, pruning, removing and pulling the image anew resolve the issue for me. Many thanks.

**Comment by Malikbadmus** [comment]
### Week 2

**Comment by DhanshreeA** [comment]
Hey @Malikbadmus good work so far. I have some notes/questions:

1. Perhaps you can experiment with other thresholds and comment on the percentage of molecules identified as hERG blockers vs non blockers. 

2. In your scatter plot, what is the X axis? From your plot it seems you're trying to plot a non numerical value ie a compound vs probability score. That isn't how scatter plots work. To make a scatter plot, I would recommend featurizing the smiles, eg, by using Morgant Fingerprints (model eos4wt0), using some form of dimensionality reduction to get them in 2 axis (X and Y), coloring them differently as blockers and non blockers as you are doing already and then plotting them in a scatter plot. A better plot suited to what you are doing, ie trying to show relative distribution of blockers vs non blockers, would be a bar chart with a binary column (0 vs 1) and their frequencies.

3. Could you provide README and also source files (if any) to document just how you procured data from ChEMBL  as well as DrugBank?

4. Regarding your threshold of 0.7, I would argue that since this is a model predicting whether a drug is toxic or not, which can potentially cause both life to loss and resources if a drug approved by this model went into production and turned out to be a False Negative, I would keep a lower threshold because in the case of toxicity, False Negatives are far more harmful than False Positives. 

5. I don't understand the last part in your notebook about converting binary predictions to probabilities. From what I can see in the notebook, they look like probabilities only.

**Comment by Malikbadmus** [comment]
@DhanshreeA , Many thanks for the review.

1. Okay, will do that

2. Thanks for the clarification. Following your suggestion, Feature extraction was done Using Morgan Fingerprints, and Principal Component Analysis (PCA) was used for dimensionality reduction. The Scatter plot has been plotted and analysis done on the plot of prediction outcomes.

3. The Github Repo README file has been updated to reflect this.

4. Yes, your argument is solid!! I've revised my analysis to emphasize this crucial point. Indeed, a model that classifies toxic substances as non-toxic poses significant risks to patients' health and well-being. Many thanks for pointing this out.

5.  Those prediction probabilities represent the likelihood of binary outcomes. The molecules in DrugBank are categorized into binary classes: inhibitors or non-inhibitors. However, each prediction also includes a probability score to measure the confidence of their predictive model on their predictions.  Looking at it now, it seems like veering into Week 3 Task, Model performance, so I'll remove it for now.

**Comment by Malikbadmus** [comment]
# **Task 2 - Model Eos30f3 Reproducibility**

**Comment by Malikbadmus** [comment]
Hello @DhanshreeA, I want to quickly clarify something, the eos30f3 model that was implemented on Ersilia is from here [Link](https://github.com/AI-amateur/DMPNN-hERG/tree/main/example_notebook/I_train_rand) and  it was trained on a datasets of around 200 molecules?

**Comment by Ajoke23** [comment]
> ## **Task 2 - Model Eos30f3 Reproducibility**
> 
> 
> ### **Identify Results you want to reproduce** 
> 
> From what can be seen from the publication, various classification models were trained using a neural network called directed message passing neural network (D-MPNN),  with diverse Datasets obtained from multiple sources to identify compounds that block hERG.
> 
> The Model with the optimal performance is `D-MPNN + moe206` with an AUC-ROC value of  **0.956 ± 0.005**.  But the  Molecular descriptor (moe206) that was used for this is closed-source, so the model that was implemented on Ersilia was trained without a molecule Featurizer.
> 
> The original D-MPNN model with an AUC-ROC value of **(AUC-ROC 0.947 ± 0.005)** is what we are going to Reproduce, it was trained on a dataset of  `7889` compounds with well-defined experimental data on the hERG and with diverse chemical structures and has 6 thresholds (10 μM, 20 μM, 40 μM, 60 μM, 80 μM, and 100 μM) for distinguishing hERG blockers from non-blockers. The Author chooses a 10 μM threshold for the model.
> 
> This dataset was assembled by Cai et al in their work published in J Chem Inf Model, 2019. 
> 
> ### **Implement the model on your system**
> 
> I cloned the model repository into my Ubuntu 22.4 system using `git clone https://github.com/AI-amateur/DMPNN-hERG.git`
> 
> The model requires Chemprop Installation, so I  navigated to the path where Chemprop is.
> ```
> cd dmpnn-herg/chemprop
> ```
> 
> Created the virtual environment installed the packages and dependencies in the `environment.yml` file and activated the environment.
> 
> ```
> conda env create -f environment.yml
> conda activate chemprop
> ```
> 
> The predictions were run with this code, `S3_no_fp_random_check` contains the five-fold model checkpoints to be used for our predictions.
> 
> ```
> python chemprop/predict.py --test_path Figure2/Cai_TableS3_fixed.csv --checkpoint_dir Figure2/S3_no_fp_random_check --preds_path chem_preds.csv
> 
> ```
> 
> The predictions were successful and saved in `chem_pred.csv`
> 
> ![new2](https://github.com/ersilia-os/ersilia/assets/46167222/f7727fab-4f41-4953-a8eb-9833d5e87f04)
> 
> They show the predicted probabilities of the compounds at various levels of potency (10 μM, 20 μM, 40 μM, 60 μM, 80 μM, and 100 μM).
> 
> 


Hi @Malikbadmus 
Pls, did you use the data used in the publication to run predictions on ersilia model eos30f3.
Based on the evaluation criteria used in the publication, you use the same evaluation criteria on the predicted values and see if you got the same result.

**Comment by Ajoke23** [comment]
> Hello @DhanshreeA @GemmaTuron , 
> I want to quickly clarify something, the eos30f3 model that was implemented on Ersilia is from here [Link](https://github.com/AI-amateur/DMPNN-hERG/tree/main/example_notebook/I_train_rand) and  it was trained on a datasets of around 200 molecules?
>  
> 

You are to use the dataset in the link you posted and it implement on ersilia model eos30f3.

**Comment by Malikbadmus** [comment]
> > Hello @DhanshreeA @GemmaTuron ,
> > I want to quickly clarify something, the eos30f3 model that was implemented on Ersilia is from here [Link](https://github.com/AI-amateur/DMPNN-hERG/tree/main/example_notebook/I_train_rand) and  it was trained on a datasets of around 200 molecules?
> 
> You are to use the dataset in the link you posted and it implement on ersilia model eos30f3.

@Ajoke23 , it belongs to a different model checkpoints.

**Comment by DhanshreeA** [comment]
> Hello @DhanshreeA @GemmaTuron , I want to quickly clarify something, the DPMN model that was implemented on Ersilia seems to be from this checkpoint [Link](https://github.com/AI-amateur/DMPNN-hERG/tree/main/example_notebook/I_train_rand) and it was trained on datasets of around 393 compounds?
> 
> While the checkpoints for the model that was trained with the `7889` Molecules is at the noFp directory [here](https://github.com/AI-amateur/DMPNN-hERG/tree/main/Figure2/S3_no_fp_random_check)

Thank you for pointing this out @Malikbadmus , this is good to know. I'll look into this with my colleagues.

**Comment by DhanshreeA** [comment]
@Malikbadmus thank you for the work so far, you can work on the task of Week 3. For this task, could you validate both the model that was trailed on the Cai et al dataset, and the one that is implemented in Ersilia?

**Comment by Malikbadmus** [comment]
> @Malikbadmus thank you for the amazing work so far, you can work on the task of Week 3. For this task, could you validate both the model that was trailed on the Cai et al dataset, and the one that is implemented in Ersilia?

Many thanks, @DhanshreeA , I will proceed to do just that.

**Comment by Malikbadmus** [comment]
# Week 3 - Validate a Model in the Wild

**Comment by DhanshreeA** [comment]
Thank you @Malikbadmus for these updates. I would say that your work is concluded and you can go ahead and create the final application!

**Comment by Malikbadmus** [comment]
Many thanks @DhanshreeA , one thing, can I help you modify the eos30f3 model implementation to the Cai et el Model checkpoints an D.C and push for a PR?

**Comment by GemmaTuron** [comment]
Hi @Malikbadmus 

Yes thanks, please fix the issue as you are right about the model checkpoints, and then focus on your final application

**Comment by DhanshreeA** [comment]
Hi @Malikbadmus I have created an issue in the model repository referencing your work here. Once you create a PR, we can link it to that issue. Good work!

**Comment by Malikbadmus** [comment]
> Hi @Malikbadmus I have created an issue in the model repository referencing your work here. Once you create a PR, we can link it to that issue. Good work!

Many thanks @DhanshreeA , PR created.

**Comment by Malikbadmus** [comment]
## WEEK 4: Submit Final Application

**Comment by Malikbadmus** [comment]
@DhanshreeA , the bug report [here](https://github.com/ersilia-os/eos30gr/issues/8)
