### ISSUE TITLE
✍️ Contribution period: Iqra Akram

### ISSUE THREAD

**Issue by Iqra350** [ersilia-os/ersilia#997]
### Week 1 - Get to know the community

- [X] Join the communication channels
- [X] Open a GitHub issue (this one!)
- [X] Install the Ersilia Model Hub and test the simplest model
- [X] Install Docker if needed, and test another model
- [X] Write a motivation statement to work at Ersilia
- [X] Submit your first contribution to the Outreachy site

### Week 2 - Get Familiar with Machine Learning for Chemistry

- [x] Select a model from the list suggested in GitBook
- [x] Download and serve the model via the Ersilia Model Hub to ensure it works
- [x] Open a repository on your GitHub user with all the necessary files
- [x] Select and clean a dataset of 1000 molecules (example notebook 1)
- [x] Run predictions for the molecules on the selected model and evaluate the results

### Week 3 - Validate a Model in the Wild

- [x] Find a suitable dataset with sufficient experimental results
- [x] Clean and standardize the dataset
- [x] Run predictions and calculate metrics.

### Week 4 - Prepare your final application

- [ ] Submit the final application in the Outreachy website

**Comment by Iqra350** [comment]
As an AI engineer, I am elated by the prospects Ersilia presents in the realm of data science. Hailing from a region where opportunities to engage with machine learning projects are scarce, I've often felt constrained by the limited avenues available to showcase and apply predictive models. My initial role as a data analyst left me yearning for deeper involvement in this dynamic and ever-evolving field. The scarcity of opportunities often led to a sense of frustration, compounded by the scarcity of roles in this burgeoning area.

However, Ersilia stands as a beacon of opportunity, offering hands-on experience and a collaborative environment that fosters growth. Working alongside esteemed scientists and fellow enthusiasts reignites my passion for data science and reinforces my programming proficiency in handling vast datasets.

Throughout my academic journey in computer science, I gravitated towards the data science domain, delving into research papers and expanding my expertise in machine learning. Despite the well-documented gender disparities in AI/ML professions, where only 26% of professionals are women, I remain resolute in my determination to excel and contribute meaningfully. Adapting to challenges faced by women in the field, I've explored diverse roles, including frontend engineering. Even after relocating, navigating through job opportunities presented its own set of hurdles.

The ethos and objectives of Ersilia resonate deeply with me. The commitment to democratize AI/ML models and ensure inclusivity in accessing advancements aligns with my personal values. Being part of such a visionary environment promises not only to make a meaningful impact but also to propel me towards new heights of influence.

I am profoundly grateful for the opportunity to collaborate with esteemed scientists and benefit from the mentorship of experienced PhD professionals. This nurturing environment not only strengthens my foundational knowledge but also fosters a culture of compassion that enriches the learning experience.

In conclusion, the Ersilia Model Hub internship embodies a pivotal opportunity for me to fuel my passion for data science and contribute to transformative projects that hold the potential to shape the future.

**Comment by Iqra350** [comment]
![Screenshot from 2024-03-06 12-51-43](https://github.com/ersilia-os/ersilia/assets/53518750/18f86737-07a0-451e-b5ea-fce529463ff8)
![Screenshot from 2024-03-06 12-52-48](https://github.com/ersilia-os/ersilia/assets/53518750/10b8543a-d7c7-41f0-8c68-a2d0643e5200)

**Comment by Iqra350** [comment]
Have not found any issue till now.

**Comment by Ajoke23** [comment]
> Have not found any issue till now. 

Well-done, you've done a great work so far. You have completed the week 1 task. 
I might just suggest you going through Ersilia model hub (https://www.ersilia.io/model-hub) to get familarize with the model since we are waiting on the team to finalize week 2 and week 3 task.

**Comment by Iqra350** [comment]
> > Have not found any issue till now.
> 
> Well-done, you've done a great work so far. You have completed the week 1 task. I might just suggest you going through Ersilia model hub (https://www.ersilia.io/model-hub) to get familarize with the model since we are waiting on the team to finalize week 2 and week 3 task.

yeah sure i am working on it. :)

**Comment by Ajoke23** [comment]
Hi @Iqra350. I noticed you're yet to complete week 2 tasks. Are you facing any challenges?
If yes, you can state them here, I will be glad to put you through

**Comment by DhanshreeA** [comment]
Hi @Iqra350 please let us know if you want to continue your work during this contribution period. Otherwise we can close this issue and focus on other applicants.

**Comment by Iqra350** [comment]
@DhanshreeA Sorry for the inconvenience. I will update all task for week 2 and 3 with in this week.

**Comment by DhanshreeA** [comment]
Hi @Iqra350 I do not see any updates yet. I am closing this issue because it will be too late to catch up with the other applicants at this point. Thank you for your time and efforts.

**Comment by Iqra350** [comment]
I am working on notebook will upload all task all together.

**Comment by Iqra350** [comment]
![Screenshot 2024-03-22 155008](https://github.com/ersilia-os/ersilia/assets/53518750/faa297d5-9d47-49ae-8be8-0c16712a9b17)
This is the proof.

**Comment by Iqra350** [comment]
Sorry for the late response i thought i have to upload all the tasks at once.

I have Uploaded the project for Week 2 and for Week 3 will upload in one or two days. Before the deadline.

You can Access my progress in link [https://github.com/Iqra350/Ersilia/blob/main/notebooks/00_model_bias.ipynb](url)

**Comment by Iqra350** [comment]
Task Complete Week 2 Task 1 [Task 1](https://github.com/Iqra350/Ersilia/blob/main/notebooks/00_model_bias.ipynb)
Task Completed Week 3 Task 3 [Task 3](https://github.com/Iqra350/Ersilia/blob/main/notebooks/02_external_validation.ipynb)

Task 2 of Week 2 is also completed but getting some issue of loading the data to orignal model of github
![Screenshot 2024-03-23 150014](https://github.com/ersilia-os/ersilia/assets/53518750/981d039b-7290-4873-8ccf-603ea3c8d1db)



I am working on it to resolve the Issue

**Comment by Iqra350** [comment]
# README for Machine Learning Model Validation Project

This repository contains the code and documentation for validating the **"eos74bo"** model from the Ersilia Model Hub, focusing on Tasks of the internship project, which involves checking model bias.

## Project Overview

The goal of this project is to validate the accuracy and reproducibility of the "eos74bo" model, which predicts ADME properties of small molecules. Task 1 specifically involves checking for model bias by running predictions for a list of 1000 diverse molecules and plotting the results in a scatter plot. and Task 2 reproducibity of results and Task 3 is extrnal data validation from Selected paper
## About Selected model

## Selected model
Kinetic aqueous solubility (μg/mL) was experimentally determined using the same SOP in over 200 NCATS drug discovery projects. A final dataset of 11780 non-redundant molecules and their associated solubility was used to train a SVM classifier. Approximately half of the dataset has poor solubility (< 10 μg/mL), and two-thirds of these low soluble molecules report values of < 1 μg/mL. A subset of the data used is available at PubChem (AID 1645848) <https://pubchem.ncbi.nlm.nih.gov/bioassay/1645848#section=Result-Definitions>.

## Characteristics
- **Input**: Compound
- **Input** Shape: Single
- **Task**: Classification
- **Output**: Probability
- **Output Type**: Float
- **Output Shape**: Single
- **Interpretation**: Probability of a compound having poor solublibity (< 10 µg/ml)

## Repository Structure

- **`README.md`**: This file, providing an overview of the project and instructions for reproducing the work.
- **`src/`**: Directory containing source code.
- **`data/`**: Directory containing datasets used for validation.
- **`results/`**: Directory containing output plots and any other result files.
- **`LICENSE`**: License file for the repository.
- **`.gitignore`**: File specifying intentionally untracked files to ignore.

## Getting Started

### Task 1 - Week 2

### Evaluating the biased
- Have used the project from the mentioned models
- Dowloaded the dataset
- Cleaned the dataset
- Converted the smiles to standard
- Generated the InchyKeys
- Made the predictions
- Ploted the scttered plot

### Task 2 - Week 2

### Reproducibility of Results

Select the paper and get the dataset that used in that paper and make prediction on that.

### The Paper is followed:

<https://slas-discovery.org/action/showPdf?pii=S2472-5552%2822%2906765-X> that used the Solubilty dataset:

### About the Code:
In this notebook, I am loading a list of molecules I obtained from PubChem for solubilty check of drug, and will replicate the results for [Ersilia Hub Model mentioned in link](https://github.com/ersilia-os/eos74bo?tab=readme-ov-file) and for the [git hub code of external sourse mentioned in link](https://github.com/ncats/ncats-adme/tree/master)processing them to make sure I have:

- Some data visulization
- Generate the ROC curve for the original github code
- Generate the ROC curves for the EMH code
  - Outcome generated after standardized smiles
- Make the comparison

**OutCome:**

- Is about the substance id highly Soluble or active class = '0' or Low Soluble or Inactive class = '0'
- Outcome is in the probability


### Task 3 - Week 3

**PAMPA, parallel artificial membrane permeability assay**: PAMPA is a laboratory test used in drug development to assess how easily a drug can pass through cell membranes. It helps researchers understand the ability of a drug to be absorbed into the bloodstream, which is important for determining its effectiveness.

### Download the  External dataset:

the code to download the dataset is below

```
from tdc.single_pred import ADME
data = ADME(name = 'PAMPA_NCATS')
split = data.get_split()

```


The github Link for the entire code is [Notebooks for All Weeks](https://github.com/Iqra350/Ersilia/tree/main/notebooks)
